#!/usr/bin/env python3
"""Optional AI audit summary for rapido-console.py, generated by shelling out to
the locally installed Claude Code CLI (claude.exe) rather than an API key --
per the user's choice, the console piggybacks on whatever login the operator
already has for their Claude account instead of managing its own credential.

Kept separate from rapido-console.py's Flask routing so it can be exercised
without pulling in Flask, mirroring the rapido_remote.py split.
"""
import glob
import json
import os
import shutil
import subprocess
from pathlib import Path
from typing import List, Optional


class AuditError(Exception):
    """Raised for any CLI-not-found, not-logged-in, or invocation failure, with
    a message safe to show directly in the console's live-status feed."""


def find_claude_cli() -> Optional[str]:
    """Locate the Claude Code CLI executable.

    Checks PATH first (works if the CLI is ever installed there), then falls
    back to the AppData install location used by the Claude desktop app on
    Windows, picking the newest version directory since that path is
    versioned and changes on update -- hardcoding one version breaks the next
    time Claude Code auto-updates.
    """
    on_path = shutil.which("claude") or shutil.which("claude.exe")
    if on_path:
        return on_path

    local_appdata = os.environ.get("LOCALAPPDATA")
    if not local_appdata:
        return None
    candidates = sorted(
        glob.glob(os.path.join(local_appdata, "Claude-3p", "claude-code", "*", "claude.exe")),
        reverse=True,  # version directories sort lexicographically close enough to newest-first
    )
    return candidates[0] if candidates else None


_PROMPT_TEMPLATE = """You are reviewing AMD server hardware audit data collected by the rapido tool. \
Below is one or more JSON documents, each the full output of a single host's hardware inventory \
(CPU, GPU, GPU health/RAS, ROCm, network, BMC, platform/BIOS, and microbenchmark results where present).

Write a concise, plain-language audit summary for an operator deciding whether this hardware is healthy \
and acceptance-ready. Structure your response as:

1. **Overall verdict** -- one or two sentences: is this node healthy, degraded, or failing acceptance?
2. **Findings by area** -- call out anything notable in GPU health/RAS (ECC errors, bad pages, XGMI errors), \
PCIe link state (degraded width/speed vs. max, replay errors), throttling/violation counters, missing tools \
that limit what could be collected, and microbenchmark results relative to theoretical peak (call out if a \
benchmark badly underperforms expectations). If a section is clean, say so briefly rather than skipping it.
3. **Recommended follow-up actions** -- a short bullet list of concrete next steps, or "None -- node looks healthy" \
if nothing is actionable.

Reference actual field names and values from the JSON when you cite something (e.g. name the specific counter \
or command that failed) rather than speaking in generalities. If two hosts are provided, explicitly call out \
differences between them as its own subsection.

{host_sections}
"""


def _host_section(index: int, path: Path, data: dict) -> str:
    hostname = (data.get("_metadata", {}) or {}).get("hostname", path.name)
    return f"### Host {index}: {hostname} ({path.name})\n```json\n{json.dumps(data, indent=2)}\n```\n"


def generate_audit_summary(json_paths: List[Path], claude_path: str, timeout: int = 180) -> str:
    """Send the collected JSON file(s) to Claude via the CLI's non-interactive
    print mode and return its narrative response.

    Raises AuditError if the CLI can't be invoked, isn't logged in, exits
    nonzero, or times out -- each mapped to one clear message so the caller
    can surface it as a status line the same way rapido_remote.RemoteError
    already is for SSH failures.
    """
    sections = []
    for i, path in enumerate(json_paths, start=1):
        try:
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            raise AuditError(f"Could not read {path.name}: {e}") from e
        sections.append(_host_section(i, path, data))

    prompt = _PROMPT_TEMPLATE.format(host_sections="\n".join(sections))

    try:
        # The prompt (JSON embedded) is well past Windows' ~32K command-line length
        # limit, so it has to go over stdin rather than as an argv element -- passing
        # it as an argument raises "WinError 206: The filename or extension is too
        # long" on real collected files.
        result = subprocess.run(
            [claude_path, "-p", "--output-format", "text"],
            input=prompt,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
    except subprocess.TimeoutExpired as e:
        raise AuditError(f"Claude CLI timed out after {timeout}s") from e
    except OSError as e:
        raise AuditError(f"Could not run Claude CLI at {claude_path}: {e}") from e

    combined = (result.stdout or "") + (result.stderr or "")
    if "Not logged in" in combined or "Please run /login" in combined:
        raise AuditError(
            "Claude CLI is not logged in on this machine. Run 'claude /login' once "
            "(outside this console) to authorize it, then retry."
        )
    if result.returncode != 0:
        raise AuditError(f"Claude CLI exited with status {result.returncode}: {combined.strip()[:500]}")
    if not result.stdout.strip():
        raise AuditError("Claude CLI returned an empty response.")

    return result.stdout.strip()
